# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4d7259686d27c6bc3278740393aa66adfaf6812e19c1681fd380406e15c47aba42b0d5483191963b7120697b160e1d902c54fbda4e20c269d885ed11b608569

test:
  secret_key_base: d93cef374c5e7f86c32af4a5abaf513b9503bd3936f70fd20cfbfdf39a8f5ca99f4877ab6d07ecd636e0b808952acf0562ec3222e70e1f8bc9b6de0b99479966

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
